version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: monday
    groups:
      gradle-updates:
        applies-to: version-updates
        patterns:
          - "*"
